image: gitpod/workspace-full:latest

tasks:
  - name: initial
    init:
      go install github.com/go-task/task/v3/cmd/task@latest
    command:
      wget https://download.oracle.com/graalvm/20/latest/graalvm-jdk-20_linux-x64_bin.tar.gz && tar zxf graalvm-jdk-*.tar.gz && mv graalvm-jdk-*/ graalvm
